### PR TITLE
 Milestone 2

### PR DESCRIPTION
**Pull request by angelacuahutle**
For this task we have:

-Declare player class 
-Defined board class

### CODE REVIEW

**Comment by angelacuahutle** [comment]
Checking linters for pull request.

**Review by GzimAsani — CHANGES_REQUESTED** [review]
# Status: Changes required :recycle: 

### Hello **team**, you have done great job so far, however in order for this project to get approved please implement the following changes:

- [x] Whenever I run `ruby bin/main.rb` I get the following error: `uninitialized constant TicTacToe (NameError)`, keep in mind that your project should run on terminal and you should implement a user interface that displays prompt for users (print/puts) and collects user input (gets.chomp) in main.rb file.
- [x] Also the following should be implemented in the game at this stage(check below): 
* [x] game asks players for their names. [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/players_names.png)
* [x] game tells which player turn it is (without computing who the winner is)[Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/player_turn.png)
* [x] game asks the player to select from available moves. [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/select_play.png)
* [x] game informs player if the selected move is invalid (without computing what an invalid move is). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/invalid_move.png)
* [x] game displays board after the player move (without computing which spots on the board are taken). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/player_turn.png)
* [x] game informs player if the selected move is a winning move (without computing the winning move). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_win%2059.png)
* [x] game informs player if the selected move is a draw move (without computing draw). [Example screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_tie.png)
* [x] game repeats all actions for the next player's move. [Example gif](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/game_flow_example.gif)
* [x] Also a loop is needed (while loop is recommended, but using any other its okay), a loop needs to be terminated at some point (after winning or draw), do not use out-of-nowhere numbers to terminate a loop like `5.times do ... end`, check the example below on how to use a loop: `
```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
````

### Please implement these changes and ask for another code review whenever you are ready

_**If you have any question related to the required changes feel free to text me on chat @GzimAsani**_

HAPPY CODING :computer: :desktop_computer:

**Comment by angelacuahutle** [comment]
Made changes as suggested

**Review by rukundoeric — APPROVED** [review]
# Status: 🍾 PROJECT APPROVED 🍾
_Excellent job on this project guys. 🎆 Keep it up._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯
  - [x] You went beyond the requirements for this milestone and implemented logic. Well done 💯

- ### To Improve
  - [x] [OPTIONAL] Remember to remove all commented codes before you request code review for the next milestone.

_Congratulations on the splendid job **@team** 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/),
Slack: Rukundo Eric**

**Pull request merged**
